## Install and configure jupyterhub server

- name: Setup generic environment
  hosts: hubs
  tasks:
    - name: Ensure hostname is set
      become: true
      tags: ["hostname"]
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    # Add relevant keys to `ssh_public_keys`
    # in either host_vars, group_vars, or local_vars.
    - name: Manage SSH public keys
      tags: ["ssh"]
      ansible.posix.authorized_key:
        user: "{{ item.value.user }}"
        state: "{{ item.value.state }}"
        key: "{{ item.value.public_key }}"
      with_dict: "{{ ssh_public_keys }}"
      when: ssh_public_keys is defined

    - name: Install Base Packages
      become: true
      tags: ["base-packages"]
      ansible.builtin.yum:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ base_packages }}"
      when: base_packages is defined

    - name: Set SELinux as permissive
      become: true
      ansible.posix.selinux:
        policy: targeted
        state: permissive

    - name: Install firewalld
      become: true
      tags:
        - firewalld
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Poke firewall holes
      become: true
      tags:
        - firewalld
      ansible.posix.firewalld:
        service: "{{ item.value.service }}"
        permanent: "{{ item.value.permanent | default('yes') }}"
        immediate: "{{ item.value.immediate | default('yes') }}"
        state: "{{ item.value.state }}"
        zone: "{{ item.value.zone }}"
      with_dict: "{{ firewalld_service_rules }}"
      when: firewalld_service_rules is defined

    - name: Install Python Environment
      become: true
      tags:
        - python
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python39
        - python39-pip
        - python39-devel

    - name: Create DHParams for SSL
      become: true
      shell: openssl dhparam -out /etc/ssl/certs/dhparams.pem 2048
      args:
        creates: /etc/ssl/certs/dhparams.pem

    #  TODO Collect and apply kernel parameters from Trevor
    #- name: Kernel parameters
    #  with_dict: "{{ kernel_tuning_params }}"

- name: Apply roles for hub
  hosts: hubs
  roles:
    - {role: geerlingguy.repo-epel, become: yes}
    - {role: weareinteractive.sudo, become: yes}
    # - {role: devsec.hardening.ssh_hardening, become: yes}

    - role: geerlingguy.nginx
      become: yes
      tags:
        - nginx

    - role: dehydrated-letsencrypt
      become: yes
      tags:
        - nginx
        - ssl

    - role: zfs
      become: true
      tags:
        - zfs

    - role: zfs-snapshot
      become: true
      tags:
        - zfs

    - role: geerlingguy.docker
      become: yes
      tags:
        - docker

    - role: docker-extra
      become: yes
      tags:
        - docker

    - role: geerlingguy.nodejs
      become: yes
      tags:
        - nodejs
        - npm

    - role: jupyterhub
      become: yes
      tags:
        - jupyter
        - jupyterhub

- name: Apply roles for markers
  hosts: markers
  roles:
    - role: rudaux
      become: yes

